latitude = 80.0
longitude = -67.0
radius = 70.0

[C201401261355A]
"II.OBN" = [ [ "R", "T", "Z",],]

[C201511132051B]
"II.OBN" = [ [ "Z",],]

[C200808071830A]
"II.OBN" = [ [ "T", "Z",],]

[C201205242247A]
"OE.DAVA" = [ [ "R", "T", "Z",],]