#!/bin/env python
from pyper.main import modules
from pyper.tools.shell import echo, exists
from pyper.pipeline import _stages

system = modules['system']

# collect stages and tasks and save to system.stage
if not hasattr(system, 'stages'):
	modules['workflow'].pipe()
	system.set('stages', _stages)

# add a seperator to output.log when restored from previous session
if exists('output/output.log'):
	echo('----------------')

# submit to job manager
system.submit()